# Generated by Django 4.0.5 on 2023-08-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='area',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='volume',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
